app:
  user-service:
    goal-service:
      max-goals-amount: 3
    premium-service:
      butch: 100

spring:
  mvc:
    servlet:
      path: /api/v1
      multipart:
        max-file-size: 5MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        profile-view: profile_view_channel
        mentorship-requested: mentorship_requested_channel
        completed-task: completed_task_channel

listeners:
  userDeactivation: true

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: user
  secretKey: password
  bucketName: corpbucket

dice-bear:
  base-url: https://api.dicebear.com
  version: 9.x
  style: bottts
  format: png

async:
  remove-premium:
    executor-name: premiumUserDeletionTaskExecutor
    corePoolSize: 5
    maxPoolSize: 30
    queueCapacity: 100

scheduled:
  remove-premium:
    cron: "0 0 0 * * SUN"

